kind: Service
apiVersion: v1
metadata:
  name: todo-list-db
spec:
  selector:
    app: todo-list
    tier: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  clusterIP: None
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: default-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: todo-list-db
spec:
  selector:
    matchLabels:
      app: todo-list
      tier: db
  serviceName: "todo-list-db"
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-list
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo:3.4.17-jessie
        command:
           - mongod
           - "--replSet"
           - rs0
           - "--smallfiles"
           - "--noprealloc"
        ports:
        - containerPort: 27017
          name: todo-list-db
        volumeMounts:
        - name: todo-list-data
          mountPath: /usr/share/mongo/data
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
          - name: MONGO_SIDECAR_POD_LABELS
            value: "app=todo-list,tier=db"
          - name: KUBERNETES_MONGO_SERVICE_NAME
            value: "todo-list-db"
  volumeClaimTemplates:
  - metadata:
      name: todo-list-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 200Mi