
db.createCollection('todo_list_counters', {
    validator: { $jsonSchema: {
        bsonType: "object",
        properties: {
          model: {
            bsonType: "number",
            description: "model name associated to the counter"
          },
          field: {
              bsonType : "string",
              description: "field used to have differente counter for the same model"
          },
          count: {
            bsonType: "number",
            description: "counter used to generate the indexes"
          }
        }
      }
    }
  });

db.getCollection('todo_list_counters').createIndex({ field: 1, model: 1 }, { unique: true });

db.createCollection('todo_lists', {
      validator: { $jsonSchema: {
        bsonType: "object",
        required: [ "id", "name" ],
        properties: {
          id: {
            bsonType: "number",
            description: "Incremental id autogenerated with secuences"
          },
          name: {
            bsonType : "string",
            description: "Name for the todo list"
          },
          next_todo_id: {
            bsonType: "number",
            description: "counter used for ToDo indexes"
          },
          creation_date: {
            bsonType: "date",
            description: "Date of creation for the List"
          },
          last_update_date: {
            bsonType: "date",
            description: "Date of last updated for the List"
          },
          todos: {
            bsonType: "array",
            items: {
              bsonType: "object",
              description: "The lis of ToDos", 
              required: [ "description", "state" ],
              properties: {
                id: {
                  bsonType: "number",
                  description: "Incremental id autogenerated based on next_todo_id from the parend document"
                },
                state: {
                  bsonType: "string",
                  description: "Incremental id autogenerated based on next_todo_id from the parend document"
                },
                description: {
                  bsonType: "string",
                  description: "The desciption of the pending task",
                }
              }
            }
          }
        }
      }
    }
  });

db.getCollection('todo_lists').createIndex({ id: 1 }, { unique: true });